[mypy]
python_version = 3.10
strict = false
warn_return_any = true
warn_unused_ignores = true
warn_redundant_casts = true
no_implicit_optional = true
check_untyped_defs = true
ignore_missing_imports = true

[mypy-evaluation.*]
ignore_errors = true
