{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sda.fullname" . }}-migrate
  labels: {{- include "sda.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "sda.labels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- include "sda.podSecurityContext" . | nindent 8 }}
      containers:
        - name: migrate
          image: {{ include "sda.backendImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["migrate"]
          securityContext: {{- include "sda.containerSecurityContext" . | nindent 12 }}
          {{- include "sda.backendEnv" . | nindent 10 }}
          resources:
            requests: {cpu: "100m", memory: 512Mi}
            limits: {cpu: "1", memory: 1Gi}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }}
